# -*- coding: utf-8 -*-

class Localization:
    eng = "eng"
    spa = "spa"
    cn = "cn"

    def __init__(self):
        pass

    @classmethod
    def get_text(cls, phrase, lan="eng"):
        english = {
            "language": "English",
            "dashboard": "Dashboard",
            "menu_one" : "Take Action!",
            "menu_two" : "Just Do it!",
            "login_sign_up": "Teacher Sign In",
            "copyright": "Copyright 2016 by Classroom Plus",
            "teacher_login": "Teacher's Sign In",
            "teacher_signup": "New Teacher Sign Up",
            "login": "Sign In",
            "signup": "Sign up",
            "remember_me": "Remember Me",
            "you_are": "You are a",
            "student": "Student",
            "teacher": "Teacher",
            "student_landing": "Welcome",
            "create": "Create",
            "save": "Save",
            "edit": "Edit",
            "update": "Update",
            "enter_a_classroom": "Enter a Classroom",
            "create_classroom": "Create a Classroom",
            "class_room_view": "Classroom View",
            "view_classroom": "Details",
            "create_quiz": "Create a Quiz",
            "create_poll": "Create a Poll",
            "new_poll": "New Poll",
            "new_quiz": "New Quiz",
            "disable": "Disable",
            "close": "Close",
            "back": "Back",
            "add": "Add",
            "add_question": "Add Question",
            "time_allowed": "Time Allowed (mins):",
            "required": "Required",
            "quiz_title": "Quiz Title",
            "yes_no": "Yes / No",
            "free_text": "Open Text",
            "multiple": "Multiple Answers",
            "single": "Single Answer",

            "404": "URL Not Found...",
            "logout": "Logout",
            "password": "Password",
            "active_polls": "Active Polls",
            "question": "Question",
            "answered": "Answered",
            "closed_polls": "Closed Polls",
            "active_quizzes": "Active Quizzes",
            "closed_quizzes": "Closed Quizzes",
            "completed": "Completed",
            "input_error": "Input Error",
            "class_access_code": "Class Access Code",
            "student_pin": "Student Pin",
            "enter": "Enter",
            "welcome": "Welcome",
            "yes": "Yes",
            "no": "No",
            "submit": "Submit",
            "time_left": "Time Left",
            "responses_here": "Responses Here",
            "thanks": "Thanks",
            "problem_occurred": "Problem Occurred",
            "poll_completed": "Poll Completed",
            "quiz_completed": "Quiz Completed",
            "poll_already_taken": "Poll Already Taken",
            "quiz_already_taken": "Quiz Already Taken",
            "class_name": "Class Name",
            "separated_by_comma": "Separated by Comma",
            "comments": "Comments",
            "go": "Go",
            "types_of_answer": "Types of Answer",
            "option": "Option",
            "options": "Options",
            "delete": "Delete",
            "poll_created_successfully": "Poll Created Successfully",
            "quiz_created_successfully": "Quiz Created Successfully",
            "account_created_successfully": "Teacher Account Created Successfully",
            "check_your_email": "We have sent you an email, please verify your account.",
            "repeat_password": "Repeat Password",
            "email": "Email",
            "name": "Name",
            "view": "View",
            "status": "Status",
            "number_of_questions": "Number of Questions",
            "type": "Type",
            "polls": "Polls",
            "quizzes": "Quizzes",
            "date": "Date",
            "answer": "Answer",
            "login_issues": "The email address or password is incorrect, please try again.",
            "student_detailed_view": "Student Detailed View",
            "take_quiz": "Take Quiz",
            "something_went_wrong": "Something when wrong with your submission, please try again.",
            "first_name": "First Name",
            "last_name": "Last Name",
            "update_question": "Update Question",
            "support": "Support",
            "forgot_password": "Forgot Your Password",
            "support_message": "Thanks for using our beta version of ClassRoom+. If you happen to experiment any problems or you need to reset your password or even have a suggestion please sent us an Email at ",
            "new_language_message": "If you would like to see a new language added to Classroom+, please sent us an Email at "
        }


        spanish = {
            "language": "Espanol",
            "dashboard": "Inicio",
            "menu_one" : "Toma Accion",
            "menu_two" : "Solo Hazlo",
            "login_sign_up": "Acceder / Crear Cuenta",
            "copyright": "Copyright 2016 Por Classroom Plus",
            "teacher_login": "Acceso de Profesores",
            "teacher_signup": "Nueva Cuenta Para Un Profesor",
            "login": "Acceder",
            "signup": "Crear Cuenta",
            "remember_me": "Recordar Me",
            "you_are": "Usted es un",
            "student": "Estudiante",
            "teacher": "Professor",
            "student_landing": "Bienvenido",
            "create": "Crear",
            "save": "Salvar",
            "edit": "Editar",
            "update": "Actualizar",
            "enter_a_classroom": "Entre a una clase",
            "create_classroom": "Crear una clase",
            "view_classroom": "Detalles de la Clase",
            "class_room_view": "Detalles de la Clase",
            "create_quiz": "Crear una prueba",
            "create_poll": "Crear una encuesta rapida",
            "new_poll": "Nueva encuesta",
            "new_quiz": "Nueva prueba",
            "quiz_title": "Titulo de la Prueba",
            "disable": "Deshabilitar",
            "close": "Cerrar",
            "back": "Volver",
            "add": "Agregar",
            "add_question": "Agregar Pregunta",
            "time_allowed": "Tiempo Permitido (minutos):",
            "required": "Requerido",
            "yes_no": "Si / No",
            "free_text": "Texto Abierto",
            "multiple": "Multiples Respuestas",
            "single": "Respuesta Unica",

            "404": "URL no encontrada...",
            "logout": "Cerrar sesion",
            "password": "Clave De Acceso",
            "active_polls": "Encuestas activas",
            "question": "Pregunta",
            "answered": "Respuesta",
            "closed_polls": "Encuestas cerradas",
            "active_quizzes": "Pruebas activas",
            "closed_quizzes": "Pruebas cerradas",
            "completed": "Completo",
            "input_error": "Error de entrada",
            "class_access_code": "Codigo de acceso a la clase",
            "student_pin": "Codigo del estudiante",
            "enter": "Entrar",
            "welcome": "Bienvenido",
            "yes": "Si",
            "no": "No",
            "submit": "Enviar",
            "time_left": "Tiempo Restante",
            "responses_here": "Respuestas aqui",
            "thanks": "Gracias",
            "problem_occurred": "Problema ocurrido",
            "poll_completed": "Encuesta completada",
            "quiz_completed": "Examen  completado",
            "poll_already_taken": "Encuesta ya tomada",
            "quiz_already_taken": "Examen ya tomado",
            "class_name": "Nombre de la clase",
            "separated_by_comma": "Separado por coma",
            "comments": "Comentarios",
            "go": "Ir",
            "types_of_answer": "Tipos de respuesta",
            "option": "Opcion",
            "options": "Opciones",
            "delete": "Borrar",
            "poll_created_successfully": "Encuesta creada con exito",
            "quiz_created_successfully": "Prueba creada con exito",
            "account_created_successfully": "Cuenta Creada Correctamente",
            "check_your_email": "Le hemos mandado un correo electronico para validar su cuenta.",
            "repeat_password": "Repite la contrasena",
            "email": "Correo Electronico",
            "name": "Nombre",
            "view": "Ver",
            "status": "Estado",
            "number_of_questions": "Numero de preguntas",
            "type": "Tipo",
            "polls": "Encuestas",
            "quizzes": "Pruebas",
            "date": "Fecha",
            "answer": "Responder",
            "login_issues": "La direccion de correo electronico o la contrasena son incorrectas. Vuelve a intentarlo.",
            "student_detailed_view": "Vista Detallada Del Estudiante",
            "take_quiz": "Tomar Examen",
            "something_went_wrong": "Algo incorrecto con tu envio, intentalo de nuevo.",
            "first_name": "Nombre",
            "last_name": "Apellido",
            "update_question": "Actualizar Pregunta",
            "support": "Soporte",
            "forgot_password": "Olvido Clave De Acceso.",
            "support_message": "Gracias por usar nuestra version beta de ClassRoom+. Si experimenta algun problema o necesita restablecer su clave de accesso o incluso tiene una sugerencia por favor envienos un correo electronico a ",
            "new_language_message": "Si desea ver un nuevo idioma agregado a Classroom +, por favor envienos un correo electronico a "


        }



        chinese = {
            "language": "中文",
            "dashboard": "控制台",
            "menu_one" : "行动!",
            "menu_two" : "说做就做!",
            "login_sign_up": "教师登陆",
            "copyright": "版权所有 2016 Classroom Plus",
            "teacher_login": "教师登陆",
            "teacher_signup": "新教师注册",
            "login": "登陆",
            "signup": "注册",
            "remember_me": "记住我",
            "you_are": "您是",
            "student": "学生",
            "teacher": "教师",
            "student_landing": "欢迎",
            "create": "新建",
            "save": "保存",
            "edit": "编辑",
            "update": "更新",
            "enter_a_classroom": "进入教室",
            "create_classroom": "新建教室",
            "class_room_view": "教室浏览",
            "view_classroom": "详情",
            "create_quiz": "新建测试",
            "create_poll": "新建投票",
            "new_poll": "新投票",
            "new_quiz": "新测验",
            "disable": "停止",
            "close": "关闭",
            "back": "返回",
            "add": "添加",
            "add_question": "添加问题",
            "time_allowed": "时间 (分钟):",
            "required": "必填",
            "quiz_title": "测试标题",
            "yes_no": "是 / 否",
            "free_text": "开放回答",
            "multiple": "多选",
            "single": "单选",

            "404": "无效链接...",
            "logout": "注销登陆",
            "password": "密码",
            "active_polls": "进行中投票",
            "question": "问题",
            "answered": "已回答",
            "closed_polls": "已关闭投票",
            "active_quizzes": "进行中测试",
            "closed_quizzes": "已关闭测试",
            "completed": "已完成",
            "input_error": "输入错误",
            "class_access_code": "课堂编号",
            "student_pin": "学生编号",
            "enter": "进入",
            "welcome": "欢迎",
            "yes": "是",
            "no": "否",
            "submit": "提交",
            "time_left": "剩余时间",
            "responses_here": "在这里回答",
            "thanks": "谢谢",
            "problem_occurred": "出现了问题",
            "poll_completed": "已完成投票",
            "quiz_completed": "已完成测试",
            "poll_already_taken": "投票已完成",
            "quiz_already_taken": "测试已完成",
            "class_name": "课程名字",
            "separated_by_comma": "用逗号分开",
            "comments": "评论",
            "go": "出发",
            "types_of_answer": "答案类型",
            "option": "选项",
            "options": "选项",
            "delete": "删除",
            "poll_created_successfully": "投票新建成功",
            "quiz_created_successfully": "测试新建成功",
            "account_created_successfully": "教师账号新建成功",
            "check_your_email": "验证邮件已发送, 请查收",
            "repeat_password": "重复密码",
            "email": "邮箱",
            "name": "名字",
            "view": "浏览",
            "status": "状态",
            "number_of_questions": "问题数量",
            "type": "类型",
            "polls": "投票",
            "quizzes": "测试",
            "date": "日期",
            "answer": "回答",
            "login_issues": "邮箱地址输入有误, 请重输",
            "student_detailed_view": "学生详情",
            "take_quiz": "做测试",
            "something_went_wrong": "提交失败，请重试",
            "first_name": "名字",
            "last_name": "姓氏",
            "update_question": "更新问题",
            "support": "支持",
            "forgot_password": "忘记密码",
            "support_message": "感谢使用我们的测试版本, 如有任何问题或者需要重置密码, 请邮件联系我们 ",
            "new_language_message": "如果您愿意为我们添加新的语言, 请邮件联系我们 "
        }

        if lan == cls.eng and phrase in english:
            return english[phrase]
        elif lan == cls.spa and phrase in spanish:
            return spanish[phrase]
        elif lan == cls.cn and phrase in chinese:
            return chinese[phrase].decode('utf-8')

        return "Error"
